apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
  labels:
    app: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv-sc
  volumes:
    - name: primeiro-pv-sc
      persistentVolumeClaim:
        claimName: pvc-2
