apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
    name: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      ## declaração de todas as variáveis do configmap:
      envFrom:
        - configMapRef:
            name: db-configmap
      # env:
      ## declaração de algumas variáveis do configmap:
      # - name: "MYSQL_ROOT_PASSWORD"
      #   valueFrom:
      #     configMapKeyRef:
      #       name: db-configmap
      #       key: MYSQL_ROOT_PASSWORD
      ## declaração de envs no arquivo:
      # - name: "MYSQL_ROOT_PASSWORD"
      #   value: "q1w2e3r4"
      # - name: "MYSQL_DATABASE"
      #   value: "empresa"
      # - name: "MYSQL_PASSWORD"
      #   value: "q1w2e3r4"
